# Homework Numpy


## **Put your name and student ID here**
## Nick Pranske, 113500528

## Numpy
Use numpy to solve questions 1-6

1. (1.5 points) Use numpy.random.randn() to generate an array **a1** with shape=(10,5), and an array **a2** with shape=(10,2).

In [1]:
import numpy as np

In [2]:
a1=np.random.randn(10,5)
a1

array([[ 0.18885576, -0.27993594,  2.22910388,  0.85637237,  0.75318933],
       [-0.41055944,  0.27161378,  0.33793257,  0.96482569, -1.22966201],
       [-1.44146607, -1.62882833,  0.45231904, -0.40979604,  0.12464798],
       [ 1.39150613,  0.1422348 ,  0.29850185, -2.03084082,  0.41443211],
       [ 0.90603802,  0.351679  ,  0.14139055, -0.42240577,  1.53808569],
       [-1.5700316 , -1.10054759,  1.26851116,  2.17279206,  0.91911331],
       [ 0.22824446,  0.62666976,  0.01549108, -0.10468657,  0.23566493],
       [ 0.0366484 , -0.66614922, -0.77321905, -1.58218081,  0.25260776],
       [-1.57211191, -2.05570827,  1.3817449 ,  2.24031602,  0.05890943],
       [ 1.32093823,  0.0090085 , -0.31401888,  1.4620351 , -0.48421807]])

In [3]:
a2=np.random.randn(10,2)
a2

array([[-0.05194884,  0.13610946],
       [-0.55660916,  0.95902899],
       [-0.37405143, -0.91075674],
       [-0.47053184, -0.39226728],
       [-0.70858777,  0.99284494],
       [ 2.39455326,  0.34417114],
       [-1.97136569,  0.75895382],
       [ 0.75445305,  0.5832315 ],
       [-0.73617836, -1.52994916],
       [ 0.25440138, -1.13187546]])

2. (1.5 points) Use hstack to stack **a1** and **a2** together to create a new array **a3**. The shape of **a3** will be (10,7)

In [4]:
a3=np.hstack([a1,a2])
a3

array([[ 0.18885576, -0.27993594,  2.22910388,  0.85637237,  0.75318933,
        -0.05194884,  0.13610946],
       [-0.41055944,  0.27161378,  0.33793257,  0.96482569, -1.22966201,
        -0.55660916,  0.95902899],
       [-1.44146607, -1.62882833,  0.45231904, -0.40979604,  0.12464798,
        -0.37405143, -0.91075674],
       [ 1.39150613,  0.1422348 ,  0.29850185, -2.03084082,  0.41443211,
        -0.47053184, -0.39226728],
       [ 0.90603802,  0.351679  ,  0.14139055, -0.42240577,  1.53808569,
        -0.70858777,  0.99284494],
       [-1.5700316 , -1.10054759,  1.26851116,  2.17279206,  0.91911331,
         2.39455326,  0.34417114],
       [ 0.22824446,  0.62666976,  0.01549108, -0.10468657,  0.23566493,
        -1.97136569,  0.75895382],
       [ 0.0366484 , -0.66614922, -0.77321905, -1.58218081,  0.25260776,
         0.75445305,  0.5832315 ],
       [-1.57211191, -2.05570827,  1.3817449 ,  2.24031602,  0.05890943,
        -0.73617836, -1.52994916],
       [ 1.32093823,  0.0090

3. (3 points) Calculate the max,min,average of each row and each column in **a3**

In [5]:
# row max
np.max(a3, axis=1)

array([2.22910388, 0.96482569, 0.45231904, 1.39150613, 1.53808569,
       2.39455326, 0.75895382, 0.75445305, 2.24031602, 1.4620351 ])

In [6]:
# row min
np.min(a3, axis=1)

array([-0.27993594, -1.22966201, -1.62882833, -2.03084082, -0.70858777,
       -1.5700316 , -1.97136569, -1.58218081, -2.05570827, -1.13187546])

In [7]:
# row average
np.mean(a3, axis=1)

array([ 0.54739229,  0.04808149, -0.59827594, -0.09242358,  0.39986352,
        0.63265168, -0.03014689, -0.19922977, -0.31613962,  0.15946726])

In [8]:
# column max
np.max(a3, axis=0)

array([1.39150613, 0.62666976, 2.22910388, 2.24031602, 1.53808569,
       2.39455326, 0.99284494])

In [9]:
# column min
np.min(a3, axis=0)

array([-1.57211191, -2.05570827, -0.77321905, -2.03084082, -1.22966201,
       -1.97136569, -1.52994916])

In [10]:
# column average
np.mean(a3, axis=0)

array([-0.0921938 , -0.43299635,  0.50377571,  0.31464312,  0.25827705,
       -0.14658654, -0.01905088])

4. (1 points) Reshape **a3** to a 2 by 35 array

In [11]:
a3.reshape(2,35)

array([[ 0.18885576, -0.27993594,  2.22910388,  0.85637237,  0.75318933,
        -0.05194884,  0.13610946, -0.41055944,  0.27161378,  0.33793257,
         0.96482569, -1.22966201, -0.55660916,  0.95902899, -1.44146607,
        -1.62882833,  0.45231904, -0.40979604,  0.12464798, -0.37405143,
        -0.91075674,  1.39150613,  0.1422348 ,  0.29850185, -2.03084082,
         0.41443211, -0.47053184, -0.39226728,  0.90603802,  0.351679  ,
         0.14139055, -0.42240577,  1.53808569, -0.70858777,  0.99284494],
       [-1.5700316 , -1.10054759,  1.26851116,  2.17279206,  0.91911331,
         2.39455326,  0.34417114,  0.22824446,  0.62666976,  0.01549108,
        -0.10468657,  0.23566493, -1.97136569,  0.75895382,  0.0366484 ,
        -0.66614922, -0.77321905, -1.58218081,  0.25260776,  0.75445305,
         0.5832315 , -1.57211191, -2.05570827,  1.3817449 ,  2.24031602,
         0.05890943, -0.73617836, -1.52994916,  1.32093823,  0.0090085 ,
        -0.31401888,  1.4620351 , -0.48421807,  0.

5. (1 points) Use ravel() to make **a3** a one-dimentional array.

In [12]:
a3.ravel()

array([ 0.18885576, -0.27993594,  2.22910388,  0.85637237,  0.75318933,
       -0.05194884,  0.13610946, -0.41055944,  0.27161378,  0.33793257,
        0.96482569, -1.22966201, -0.55660916,  0.95902899, -1.44146607,
       -1.62882833,  0.45231904, -0.40979604,  0.12464798, -0.37405143,
       -0.91075674,  1.39150613,  0.1422348 ,  0.29850185, -2.03084082,
        0.41443211, -0.47053184, -0.39226728,  0.90603802,  0.351679  ,
        0.14139055, -0.42240577,  1.53808569, -0.70858777,  0.99284494,
       -1.5700316 , -1.10054759,  1.26851116,  2.17279206,  0.91911331,
        2.39455326,  0.34417114,  0.22824446,  0.62666976,  0.01549108,
       -0.10468657,  0.23566493, -1.97136569,  0.75895382,  0.0366484 ,
       -0.66614922, -0.77321905, -1.58218081,  0.25260776,  0.75445305,
        0.5832315 , -1.57211191, -2.05570827,  1.3817449 ,  2.24031602,
        0.05890943, -0.73617836, -1.52994916,  1.32093823,  0.0090085 ,
       -0.31401888,  1.4620351 , -0.48421807,  0.25440138, -1.13

6. (2 points) Use linspace() to create a **1D** array **a6**, start from 1, end with 20, 100 points, and then reshape it to a 10 by 10 array.

In [13]:
a6=np.linspace(1,20,100)
a6.reshape(10,10)

array([[ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
         1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273],
       [ 2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
         3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465],
       [ 4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
         5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657],
       [ 6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
         7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848],
       [ 8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
         9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ],
       [10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
        11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232],
       [12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
        13.47474747, 13.66666667, 13.85858586